### ISSUE TITLE
durable persistence not working

### ISSUE THREAD

**Issue by krishna81m** [Romeh/spring-boot-ignite#2]
Tried restarting and checking the same value several times in cache by putting a break point in 
```
com.romeh.ignitemanager.repositories.impl.IgniteAlertsStore#createAlertEntry
...
alertsCache.put(alertEntry.getAlertId(), alertEntry)
```

But, I don't see that the value is found in cache, with persistence to disk enabled, shouldn't it be able to find the cache populated on restart?

I even tried:
```
alertsCache.query(
        new SqlFieldsQuery("select serviceId from AlertEntry")).getAll()
;


```

**Comment by Romeh** [comment]
now it is working fine , just clean ur local workspace

**Comment by krishna81m** [comment]
could you elaborate more please, what am I cleaning and how do I check that persistence is working?

**Comment by Romeh** [comment]
you just need to check out master in a fresh work space folder the do the following :
1- start the application , open the swagger UI where u can call rest APIs there from the UI without rest client 
2- add an alert , then call get all alerts to check if it is added correctly 
3- restart your java application from ur IDEA
4- call again get alerts , you should see ur old added entry being returned in the response
